### ISSUE TITLE
 fatal: not a git repository (or any of the parent directories)

### ISSUE THREAD

**Issue by odiazib** [eagles-project/haero#421]
I am getting this warning message, fatal: not a git repository (or any of the parent directories): .git, after make:

make 
[ 24%] Built target kokkoscore
[ 26%] Built target kokkoscontainers
[ 28%] Built target kokkossimd
[ 61%] Built target yaml-cpp
[ 69%] Built target spdlog
[ 81%] Built target ekat
[ 83%] Built target ekat_test_main
[ 85%] Built target ekat_test_session
[ 86%] Updating haero version information...
fatal: not a git repository (or any of the parent directories): .git
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch

**Comment by jeff-cohere** [comment]
Is this something you see when you build using the `build-haero.sh` script? It shouldn't happen unless you build Haero outside of a cloned git repository.

**Comment by odiazib** [comment]
I am getting this warning message if I use this script: https://github.com/eagles-project/haero/blob/main/setup

Using build-haero.sh does not produce that warning message.

**Comment by jeff-cohere** [comment]
Can you paste the commands you're using to run `setup` and `make`?

**Comment by odiazib** [comment]
./setup ../build

cd ../build/

then I modify config to set 
ENABLE_MPI=OFF and ENABLE_GPU=ON 

In weaver I change the compilers.

From
CXX=c++
CC=cc
FC=gfortran

to
CXX=g++
CC=gcc
FC=gfortran

then in ../build and do make. 

Thus, I am building outside of the cloned git repository. 

But, Haero builds without issues.

**Comment by jeff-cohere** [comment]
> Thus, I am building outside of the cloned git repository.

That explains it. The warning isn't harmful, but I could make silence it or make it more "friendly" if we wanted. Do you have a suggestion?

**Comment by jeff-cohere** [comment]
Suggestion: can the script try to find a relevant Git repo for Haero? Or should we just say that it's not being configured from a Git repo?
