### ISSUE TITLE
Switch ColumnView from managed to unmanaged Kokkos View

### ISSUE THREAD

**Issue by jeff-cohere** [eagles-project/haero#444]
Now that we're actually starting to plug Haero and mam4xx into eamxx, we need to adopt a memory model that is compatible with the treatment of tracers within eamxx's atmosphere driver (AD). Currently, our `ColumnView` type is a 1D managed view representing an atmospheric column, and it needs to be changed to an equivalent unmanaged view.

We are using these ColumnViews in two different contexts right now:

1. Standalone aerosol package development, in which we treat ColumnViews as managed views, because the `Atmosphere` and related column-oriented data types don't share their resources with a host model
2. The integrated atmosphere-aerosol model, in which the host model owns the storage for our aerosol data, and the aerosol package just manipulates the stored data

I think the easiest way to provide ColumnViews for both of these contexts is to give Haero an allocation pool from which "standalone" ColumnViews can be created for testing, etc. **Then the only thing we need to change in our current approach is to call a function (e.g. `NewColumnView(nlev)`) that allocates an unmanaged `ColumnView` from this allocation pool.** We'd call this function from our test code and in any constructors that allocate column data given only the number of vertical levels (e.g. the `Atmosphere` class and the mam4xx `Prognostics` and `Diagnostics` classes).

In the integrated atmosphere-aerosol model, we don't need the Haero allocation pool unless we want to create truly temporary views, since EAMxx's AD allocates all the storage we need via the FieldManager.

I'm doing this work in the [jeff-cohere/uviews](https://github.com/eagles-project/haero/tree/jeff-cohere/uviews) branch.

FYI @overfelt

**Comment by overfelt** [comment]
Would it be easier to template on the view type?  Managed or Unmanaged?

**Comment by jeff-cohere** [comment]
We actually used to do that in the previous incarnation, but this would not allow us to run our standalone tests in configurations where we integrate with eamxx (at least not the way I imagine it). But if I'm missing something and you have an idea about how to do testing this way, we should discuss.

**Comment by jeff-cohere** [comment]
This went in with #445
